# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Biological Variation Data
#'
#' @title Simulate Biological Variation Data
#' @name simulate_bv_data
#'
#' @param n \code{Integer}. The number of subjects.
#' @param S \code{Integer}. The number of samples taken from each subject. Defaults to 10.
#' @param R \code{Integer}. The number of replicates measured for each sample. Defaults to 2.
#' @param cvi \code{Double}. The coefficient of variation (in percent) for variability within each subject (default is 10).
#' @param cva \code{Double}. The coefficient of variation (in percent) for the variability of analytical error (default is 2). This is the source of variation between replicated measurements.
#' @param cvg \code{Double}. The coefficient of variation (in percent) for variability between subjects (default is 50).
#' @param mu \code{Double}. The overall true mean for the population (default is 100).
#'
#' @description This function simulates biological variation data based on a specified number of subjects, samples, and replicates.
#' @details This function generates simulated biological variation data. It first generates subject-specific means based on a normal distribution with mean `mu` and coefficient of variation `cvg`. For each subject, it then generates `S` samples based on their specific mean and the coefficient of variation `cvi`. Finally, for each sample, it generates `R` replicate measurements based on the sample mean and the coefficient of variation `cva`.
#'
#' @return A `list` with columns:
#' \itemize{
#'   \item \code{SubjectID} - The ID of the subject.
#'   \item \code{SampleID} - The ID of the sample.
#'   \item \code{ReplicateID} - The ID of the replicate.
#'   \item \code{y} - The measured value for the replicate.
#' }
#'
#' @examples
#' \dontrun{
#' # Simulate data for 100 subjects, with 10 samples per subject and 3 replicates per sample
#' output <- simulate_bv_data(15, 10, 2, 10, 2, 50, 100)
#' print(output)
#' }
#'
NULL

simulate_bv_data <- function(n, S = 10L, R = 2L, cvi = 10, cva = 2, cvg = 50, mu = 10) {
    .Call(`_biovar_simulate_bv_data`, n, S, R, cvi, cva, cvg, mu)
}

