# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' One Way and Two Way ANOVA Modelling Based on Biological Variation Data
#'
#' @title One Way and Two Way ANOVA Modelling Based on Biological Variation Data
#' @name bv_anova
#'
#' @param data \code{data.table} or \code{list} object, with the following columns or elements:
#' \itemize{
#'   \item \code{SubjectID} - \code{Integer} vector with the IDs of the subjects.
#'   \item \code{SampleID} - \code{Integer} vector with the IDs of the samples.
#'   \item \code{ReplicateID} - \code{Integer} vector with the IDs of the replicates.
#'   \item \code{y} - \code{Numeric} vector with the measured values for each combination of IDs.
#' }
#' 
#'
#' @description This function uses biological variation data to estimate both one-way (one model for each subject) and two-way (general model overall subjects) nested ANOVA models. 
#' @details The components of the estimated model can be used to estimate intra biological variation, inter biological variation and analytical variation, with corresponding confidence intervals. The model estimates relies on that all model effects are mutually independent and normally distributed.
#'
#' @return A \code{list} containing all relevant information for the nested ANOVA model fit.
#'
#' @examples
#' \dontrun{
#' # Simulate data for 15 subjects, with 10 samples per subject and 3 replicates per sample
#' output <- simulate_bv_data(15, 10, 2, 10, 2, 50, 100)
#' anova_fit <- bv_anova(output)
#' print(anova_fit)
#' }
#'
NULL

bv_anova <- function(data) {
    .Call(`_biovar_bv_anova`, data)
}

#' Simulate Biological Variation Data
#'
#' @title Simulate Biological Variation Data
#' @name simulate_bv_data
#'
#' @param n \code{Integer}. The number of subjects.
#' @param S \code{Integer}. The number of samples taken from each subject. Defaults to 10.
#' @param R \code{Integer}. The number of replicates measured for each sample. Defaults to 2.
#' @param cvi \code{Double}. The coefficient of variation (in percent) for variability within each subject (default is 10).
#' @param cva \code{Double}. The coefficient of variation (in percent) for the variability of analytical error (default is 2). This is the source of variation between replicated measurements.
#' @param cvg \code{Double}. The coefficient of variation (in percent) for variability between subjects (default is 50).
#' @param mu \code{Double}. The overall true mean for the population (default is 100).
#'
#' @description This function simulates biological variation data based on a specified number of subjects, samples, and replicates.
#' @details This function generates simulated biological variation data. It first generates subject-specific means based on a normal distribution with mean `mu` and coefficient of variation `cvg`. For each subject, it then generates `S` samples based on their specific mean and the coefficient of variation `cvi`. Finally, for each sample, it generates `R` replicate measurements based on the sample mean and the coefficient of variation `cva`.
#'
#' @return A `list` with columns:
#' \itemize{
#'   \item \code{SubjectID} - The ID of the subject.
#'   \item \code{SampleID} - The ID of the sample.
#'   \item \code{ReplicateID} - The ID of the replicate.
#'   \item \code{y} - The measured value for the replicate.
#' }
#'
#' @examples
#' \dontrun{
#' # Simulate data for 100 subjects, with 10 samples per subject and 3 replicates per sample
#' output <- simulate_bv_data(15, 10, 2, 10, 2, 50, 100)
#' print(output)
#' }
#'
NULL

simulate_bv_data <- function(n, S = 10L, R = 2L, cvi = 10, cva = 2, cvg = 50, mu = 10) {
    .Call(`_biovar_simulate_bv_data`, n, S, R, cvi, cva, cvg, mu)
}

